<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Simple Chat</title>
    <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
</head>
<body>
<h1>Simple Ugly Chat</h1>
<div id="messagesDiv"></div>
<input type="text" id="message" /><button type="button" onclick="sendMessage();">Send</button>
<script>
    var chatURL = 'ws://' + window.location.hostname + ':8282';
    var chatConn = null;
    jQuery(function(){
        chatConn = new WebSocket(chatURL);
        chatConn.onmessage = function(e){
            try {
                var incomingMessage = JSON.parse(e.data);
                var $newdiv = $( "<div class='message'>"+incomingMessage.message+"</div>" );
                jQuery('#messagesDiv').append($newdiv)
            } catch (e) {
                console.log(e + ': ' + e.data);
            }
        }
        jQuery('#message').on('keyup',function(e){
            e.preventDefault();
            if (e.keyCode===13) sendMessage();
        })
    });
    function sendMessage(){
        var message = jQuery('#message').val();
        jQuery('#message').val('');
        if (message!='') chatConn.send(JSON.stringify({'route': 'Chat', 'action': 'message', 'message': message}));
    }
</script>
</body>
</html>